### ISSUE TITLE
Package-Manager Install

### ISSUE THREAD

**Issue by andrzejmy** [petermorlion/RedStar.Amounts#2]
Hello,

I am trying to download your library using the package manager console but got following error:

_"Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'RedStar.Amounts 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
"_

Trying on different FrameworkVersions but on all got similar issue.

Using Visual studio 2015 if that matter.

Regards
Andy

**Comment by petermorlion** [comment]
Hi Andy,

I'm not behind a pc now, but I can check later. However, I guess you're trying to install the latest version which targets .net standard 2.0, while your target framework, .net framework 4.5.1, doesn't support that standard. Off the top of my head, I think you're on .net standard 1.3, but not sure.

Can you try installing RedStar.Amounts 1.5?

Again, I'll check on my pc later and get back to you.

**Comment by petermorlion** [comment]
I can confirm you can install [RedStar.Amounts 1.5](https://www.nuget.org/packages/RedStar.Amounts/1.5.0) in a .NET 4.5.1 library:

```
Install-Package RedStar.Amounts -Version 1.5
```
