### ISSUE TITLE
_equalityPrecision should be an amount

### ISSUE THREAD

**Issue by uncle-buzz** [petermorlion/RedStar.Amounts#4]
We agreed that to round, the unit could be ignored because rounding is about rendering, not about accuracy in calculation or comparison.
But for _equalityPrecision, the unit is important: in your comparison, the 2nd amount is converted to the first unit, so the accuracy of the first amount is used for the comparison. Even with the same _equalityPrecision, the == operator will not give you the same result depending on the amount used first:
```
var A = new Amount(100.01, "liter");
var B = new Amount(100, "liter");
B.EqualityPrecision = 1;
A == B // false : round(100.01,8) == round(100,8) => 100.01 != 100
B == A // true : round(100.01,1) == round(100,1) => 100.0 == 100
```
In my example, I used same unit but different precision, but it's the same result with same precision but different unit, since 8 mbar precison won't give same result than 8 psi precision.
To be correct, the precision should be expressed as an amount, and we should use the lower precision of both amount and converting them to this unit.
```
var A = new Amount(100, "liter"); // default precision = 10-9 liter
var B = new Amount(100.01, "liter"); // default precision = 10-9 liter
B.EqualityPrecision = new Amount(1, "deciliter");
A == B // true : Abs(A - B) < Max(A.EqualityPrecision, B.EqualityPrecision) => 0.01 liter < 1 deciliter
B == A // true : Abs(B - A) < Max(B.EqualityPrecision, A.EqualityPrecision) => 0.01 liter < 1 deciliter
```
Result of operations should take the lower precision, and to be immutable, precision should be readonly and set in constructor.

**Comment by uncle-buzz** [comment]
ToString formatProvider should be adapted with precision : 
100.01 liter with 0.1 liter precision shouldn't be displayed with more than 1 decimal, even if I ask for 3 decimales in formatProvider since decimales under precision are not significants

**Comment by petermorlion** [comment]
Agreed, the equalityprecision should be an amount. Then you can say, for example, you're measuring to 1cm precision, instead of measuring to, uh, 1.
You're obviously well-versed in this domain. Can you tell me the rationale behind your statement that operations should take the lower precision? And why the precision should be readonly?
I'm not sure I agree the formatprovider should use the precision though. If I measure 100 cm but want to display it as 100.00, I should be able to. If I want, I could use use the precision to decide how I want to display the amount.

**Comment by uncle-buzz** [comment]
If you take an amount of about 3kg, and add 3g, you can't say result is 3.003kg because 3kg is a rounded value, maybe you had 2.926kg, so result would be 2.929kg, not 3.003kg
The lower precision (maximum imprecision amount) is preponderant and should be propagate at each operation (+ and -).
It's the same reason why precision should be readonly, and why you shouldn't be able to print more precision than you have : 
100cm rounded at 1cm could be 99.51cm or 100.42cm before rounding, so printing 100cm is correct, printing 100.0 or 100.00cm is incorrect because 100.00cm means 100cm with 0.01cm precision
100cm == 99.51cm won't return same result with 1cm or with 0.01cm precision, so precision is part of amount and changing precision is like changing value, it will change the amount.
Sorry for my english, I hope you understand what I mean.

**Comment by uncle-buzz** [comment]
Another way to demonstrate the propagation of lower precision : 
if you add an amount of about 1.0km (1hm precision) to 1005m (1m precision), you can decompose the operation like this : 
1.0km is like 10hm (exact) + unknow amount (1m)
1005m is like 10hm (exact) + 5m (1m)
so 1.0km + 1005m is like 10hm + 10hm = 20 hm (exact) and 5m + unknow amount = unknow amount.
20hm + unknow amount (1m) = unknow amount (1m), but with 1hm precision we have 20hm + 0hm since we know the unknow amount is smaller than 1hm.
Final result is 20hm, or 2.0km with 1hm precision, we lost the 1m precision of 2nd amount.

**Comment by petermorlion** [comment]
I agree the lower precision (higher number) takes prevalence. But where did the 5m go? I'd think that if you have a measurement of:

1km ± 1hm = somewhere between 900m and 1100m

and

1005m ± 1m = somewhere between 1004m and 1006m

Add the two together and you should have somewhere between 1904m and 2106m, which is actually 2005m ± 101m. So you'd have to add the precision. This is also explained [here](http://www.batesville.k12.in.us/physics/APPhyNet/Measurement/Calc_With_Measure.html) though, as they say, it is very unlikely that the uncertainties are both there maximum at the same time. They too state that the lower precision can be taken (and provide the mathematical explanation as to why). I've read similar explanations elsewhere.

So there seem to be two possible options that are both correct? Let me think on this for a while.

Some other references:
- https://www.thestudentroom.co.uk/showthread.php?t=2661762
- http://spiff.rit.edu/classes/phys273/uncert/uncert.html
- https://physics.stackexchange.com/questions/392016/uncertainty-in-the-average-of-two-measurements-with-their-respective-uncertaint/392042#392042
- http://lectureonline.cl.msu.edu/~mmp/labs/error/e2.htm

**Comment by uncle-buzz** [comment]
In fact, you have to add uncertainties, but this is a mathematical fact. In real world, you have to add similar uncertainties, but if there is some magnitudes between uncertainties, it's a non sens to keep the small one.
100m = 1.00hm, but 1hm != 100m, 1hm = [5 - 14]dam = [45-144]m = [445-1444]cm ... rounded at 1hm precision
so a precision of 1hm can't be convert to 100m.
To my mind, we have to convert amount in lower presision unit, and add precisions : 
1km ±100m + 1005m ±1m <=> 1000m ±100m + 1005m ±1m = 2005m ± 101m; 
1km ±1hm + 1005m ±1m <=> 10hm ± 1hm + 10hm ±0hm = 20hm ±1hm <=> 2km ±1hm
so 1hm != 100m

For implementation, You can add a RealAmount class, child of Amount class with an amount included as precision.

**Comment by petermorlion** [comment]
I put this on the physics stackexchange too, and got an [interesting answer](https://physics.stackexchange.com/questions/415786/adding-uncertainties-when-you-cannot-make-any-assumptions-about-the-measurements/415847#415847). So it depends on who your audience is. I'll ponder over this for a while. There are possible solution, but I don't know yet how far I want to go.

**Comment by uncle-buzz** [comment]
Well, there are in fact differents things behind precision...
I have at least 2 in mind : 

- precision of measure, when you use a sensor to measure a physical quantity, the value you read contains some uncertainties from repeatability default (not always the same value is returned for the same measure), accuracy of the sensor (difference between the value returned by sensor and the real value) and this default is generally a Gaussian standard deviation as said in physics stackexchange.
your measure is 1.024 ± 0.1m, your sensor measures exactly 1.024m, but you know the error could be of 0.1m (maximum error). Since it's a Gaussian deviation, you are probably near 1.024m, but you could be exceptionnally at 1.124m

- resolution of sensor, because you are not able to make difference between 2 very near values, because difference is too small, or because you use a numeric conversion with 16bit resolution... so the measure you read is a rounded value to the pitch of your system. If your pitch is 0.1m, your measure will be 1.0m, but the real value is between 0.95 and 1.04m
In these case, the probabilities to be at 1.00 or 0.97 or 1.03m are the same

So, if the software is about scientist calculation, the first notion is important.
If the software is about sensor reading, resolution is important.

If you want to make scientist calculation from sensor reading, you need both...

Precision is about  how precise are your value, it's a theoric value to give with the main value, like 1.024 ± 0.1m

Resolution is about rounded value, when you read 1.024m with 1mm resolution, real value could be 1.024 ± 0.0005m

For addition, we have to consider both notion, but for comparison method, only the resolution is pertinent : 
- precision: 1.024 ± 0.1m != 1.015 ± 0.1m, even if there is a probability than both values represents the same real value.
- resolution: 1.024m == 1.015m with 0.1m resolution because it's 1.0 == 1.0 if you apply resolution (and it's where the bigger resolution "eats" the small one if there are differents resolution)

Tolerance is another different thing to my mind, it's about what we want, not what we have. it's a target defined by 2 limits. Only the representation looks like a precision

**Comment by petermorlion** [comment]
I think this change would take me too far for the amount of usage this library has. Changing could lead to unexpected results for existing users too, I fear. I guess the term "equalityPrecision" is what it is: the precision used to compare equality. It's not the scientific concept of precision. If this ever comes up again, I'm willing to revisit the issue. But I don't feel it's currently worth it.
